WebApplication.Web/ViewComponents/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Web.Providers.Auth;

namespace WebApplication.Web.ViewComponents
{
    /// <summary>
    /// A view component is a reusable or "isolated" piece of our app.
    /// It cannot be navigated to via URL like a controller.
    /// </summary>
    public class NavBarViewComponent : ViewComponent
    {
        // Components allow dependency injection just like controllers.
        private IAuthProvider authProvider;
        public NavBarViewComponent(IAuthProvider authProvider)
        {
            this.authProvider = authProvider;
        }

        /// <summary>
        /// This is the method that is invoked when the component is told to "render".
        /// </summary>
        /// <returns></returns>
        public IViewComponentResult Invoke()
        {
            var user = authProvider.GetCurrentUser();
            return View("_NavBar", user);
        }
    }
}

WebApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication.Web</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <div class="top">
        <header class="header">
            <img src="~/images/logo.png" />
        </header>

        <nav class="nav">
            <ul>
                <li><a asp-controller="home" asp-action="Index">Home</a></li>
                <li><a asp-controller="user" asp-action="Survey">Survey</a></li>
            </ul>

            <ul class="user-nav">
                @await Component.InvokeAsync("NavBar") @* Render the NavBar component. *@
            </ul>

        </nav>
    </div>

    <main>
        @RenderBody()
    </main>

    <footer class="footer">
        <p>&copy;@DateTime.Now.Year Tyler Teran <img src="~/images/backpack.png" /> Ryan Pearce <img src="~/images/backpack.png" /></p>
    </footer>
</body>

</html>